# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  lucas-postgres-data:
    driver: local

services:
  # Postgres (10.3)
  postgres:
    image: postgres:10.3
    container_name: lucas-postgres
    volumes:
      - lucas-postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5433"
    environment:
      - POSTGRES_PASSWORD=lucas
      - POSTGRES_DB=lucas
      - POSTGRES_USER=lucas

  # PHP (with Nginx)
  # you can change from nginx to apache, just change session 'image'
  app:
    image: ambientum/php:7.2-nginx
    container_name: lucas-app
    volumes:
      - .:/var/www/app
    ports:
      - "8080:8080"
    links:
      - postgres
